import {MATRICES_SHA256} from './matrices-lock.mjs';
const languages={ja:'日語',ko:'韓語',th:'泰語',en:'英語'};
const names={curriculum:'學習目標',grammar:'文法用法',vocabulary:'主題詞彙'};
export function filterRows(rows,{lang='all',band='all',status='all',search=''}={}){
 return rows.map(r=>({...r,members:r.members.filter(m=>(lang==='all'||m.language===lang)&&(band==='all'||m.level===band)&&(status==='all'||m.review===status)&&(!search||JSON.stringify([r.title,r.id,m]).toLowerCase().includes(search.toLowerCase())))})).filter(r=>r.members.length);
}
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
export async function loadMatrices(fetcher=fetch){const response=await fetcher('./matrices.json');if(!response.ok)throw Error('無法載入內容，請稍後再試。');const raw=await response.arrayBuffer();const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',raw))].map(x=>x.toString(16).padStart(2,'0')).join('');if(digest!==MATRICES_SHA256)throw Error('內容更新中，請重新整理後再試。');return JSON.parse(new TextDecoder().decode(raw));}
function clean(text){return String(text).split(/(?<=[。；])/).filter(s=>!/(sourceLevels|proposedLevel|SHA256|runtime|proposal|KnowledgeItem|未映射|知識ID|逐義CEFR|官方分級|逐項官方|來源狀態|綱要|review|TSV|本案|本片)/i.test(s)).join('').trim();}
async function mount(){const out=document.querySelector('#matrix-results');try{const data=await loadMatrices();const requested=new URL(location.href).searchParams.get('matrix')||'curriculum';if(!names[requested])throw Error('找不到這張矩陣。請使用上方入口。');document.querySelector(`[href="?matrix=${requested}"]`).setAttribute('aria-current','page');const rows=data.matrices[requested];const scope={curriculum:'從初次見面到表達看法，依程度探索 144 個學習目標。',grammar:'依情境查找 31 組文法用法，了解各語的說法與使用條件。',vocabulary:'探索飲食、購物、個人物品、衣著與顏色等 14 類主題詞彙。'};document.querySelector('#scope').textContent=scope[requested];let limit=6;
 function render(){const filters={lang:document.querySelector('#lang').value,band:document.querySelector('#band').value,status:document.querySelector('#status').value,search:document.querySelector('#search').value.trim()};const filtered=filterRows(rows,filters);out.replaceChildren();document.querySelector('#count').textContent=`${names[requested]} · ${filtered.length} 個主題 · 顯示 ${Math.min(limit,filtered.length)} 個`;if(!filtered.length)out.append(el('p','找不到符合條件的內容，試試其他關鍵字或級別。','empty'));
 for(const row of filtered.slice(0,limit)){const section=el('section',undefined,'matrix-row');section.append(el('h2',row.title.replace(/^已有｜/,'')));if(requested==='curriculum')section.append(el('p',row.description));const grid=el('div',undefined,'language-grid');for(const [lang,label]of Object.entries(languages)){if(filters.lang!=='all'&&filters.lang!==lang)continue;const card=el('article',undefined,'language-card');card.append(el('h3',label));const members=row.members.filter(m=>m.language===lang);if(!members.length)card.append(el('p','此語沒有符合條件的資料。'));for(const m of members){const e=el('div',undefined,'entry');e.append(el('span',m.review==='accepted-outline'?'已核對':m.review==='missing-reference'?'資料待補':'待核對','badge '+(m.review==='accepted-outline'?'accepted':'')),el('h4',m.title),el('p',`${m.level==='undetermined'?'尚未分級':m.level}`));if(m.detail.sense)e.append(el('p',m.detail.sense.definition));const detail=el('details');detail.append(el('summary',requested==='curriculum'?'學習重點':'怎麼使用'));
 if(m.detail.sense){const sense=m.detail.sense;for(const [key,label] of [['function','用途'],['conditions','使用條件'],['exclusions','注意事項']]){if(sense[key])detail.append(el('h4',label),el('p',clean(sense[key])));}for(const form of m.detail.forms||[]){detail.append(el('p',form.text));if(form.conditions)detail.append(el('p',clean(form.conditions)));}}
 else if(requested==='curriculum'){if(m.detail.inLessonSupport?.length){detail.append(el('h4','你會學到'));for(const x of m.detail.inLessonSupport)detail.append(el('p',clean(x)));}if(m.detail.prerequisites?.length){detail.append(el('h4','先會這些更容易'));for(const x of m.detail.prerequisites)detail.append(el('p',clean(typeof x==='string'?x:x.description||'')));}detail.append(el('p','教材準備中'));}
 e.append(detail);card.append(e);}grid.append(card);}section.append(grid);out.append(section);}document.querySelector('#more').hidden=limit>=filtered.length;}
 document.querySelector('#matrix-filters').addEventListener('input',()=>{limit=6;render();});document.querySelector('#matrix-filters').addEventListener('submit',e=>e.preventDefault());document.querySelector('#more').addEventListener('click',()=>{limit+=6;render();});render();}catch(e){out.replaceChildren(el('p',e.message,'empty'));document.querySelector('#scope').textContent='暫時無法載入學習內容。';}}
if(typeof document!=='undefined'&&document.querySelector('#matrix-results'))mount();
