import {MATRICES_SHA256} from './matrices-lock.mjs';
const languages={ja:'日語',ko:'韓語',th:'泰語',en:'英語'};
const names={curriculum:'學習目標',grammar:'文法用法',vocabulary:'主題詞彙'};
export function filterRows(rows,{lang='all',band='all',status='all',search=''}={}){
 return rows.map(r=>({...r,members:r.members.filter(m=>(lang==='all'||m.language===lang)&&(band==='all'||m.level===band)&&(status==='all'||m.review===status)&&(!search||JSON.stringify([r.title,r.id,m]).toLowerCase().includes(search.toLowerCase())))})).filter(r=>r.members.length);
}
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
export async function loadMatrices(fetcher=fetch){const response=await fetcher('./matrices.json');if(!response.ok)throw Error('無法載入內容，請稍後再試。');const raw=await response.arrayBuffer();const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',raw))].map(x=>x.toString(16).padStart(2,'0')).join('');if(digest!==MATRICES_SHA256)throw Error('內容更新中，請重新整理後再試。');return JSON.parse(new TextDecoder().decode(raw));}
function clean(text){return String(text).split(/(?<=[。；])/).filter(s=>!/(sourceLevels|proposedLevel|SHA256|runtime|proposal|KnowledgeItem|未映射|知識ID|逐義CEFR|官方分級|逐項官方|來源狀態|綱要|review|TSV|本案|本片)/i.test(s)).join('').trim();}
export function mount(data, root=document.querySelector('#app')) {
 const initial=new URL(location.href).searchParams.get('matrix');
 let state={lang:null,kind:names[initial]?initial:'curriculum',band:'A1',page:0,row:null,item:0,search:''};
 const pageSize=5;
 function button(text,fn,cls=''){const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;}
 function move(patch){state={...state,...patch};history.pushState(state,'','#'+(state.lang||'start')+'/'+state.kind+(state.row?'/topic':''));render();window.scrollTo(0,0);}
 window.addEventListener('popstate',e=>{state=e.state||{...state,lang:null,row:null,page:0};render();});
 function rows(){return filterRows(data.matrices[state.kind],{lang:state.lang,band:state.band,search:state.search});}
 function pager(current,total,change){const nav=el('nav',undefined,'pager');nav.setAttribute('aria-label','分頁');const prev=button('上一頁',()=>change(current-1));prev.disabled=current===0;const next=button('下一頁',()=>change(current+1));next.disabled=current>=total-1;nav.append(prev,el('span',`${current+1} / ${Math.max(1,total)}`),next);return nav;}
 function render(){root.replaceChildren();
 if(!state.lang){root.append(el('p','每天一點，走進另一種語言。','eyebrow'),el('h1','今天想學哪種語言？'),el('p','選一種語言，找到適合你的學習起點。','intro'));const grid=el('div',undefined,'language-picker');for(const [code,name] of Object.entries(languages)){const native={ja:'日本語',ko:'한국어',th:'ภาษาไทย',en:'English'}[code];const b=button('',()=>move({lang:code,page:0,row:null}),'language-choice');b.append(el('strong',name),el('span',native),el('span','開始探索 →','arrow'));grid.append(b);}root.append(grid);return;}
 const top=el('div',undefined,'toolbar');top.append(button('← '+(state.row?'返回主題':'選擇語言'),()=>move(state.row?{row:null,item:0}:{lang:null,row:null}),'back'),el('span',languages[state.lang]+' · '+state.band));root.append(top);
 if(state.row){const row=rows().find(r=>r.id===state.row);if(!row){root.append(el('p','這個主題目前沒有內容。'));return;}const m=row.members[state.item];root.append(el('p',names[state.kind],'eyebrow'),el('h1',row.title.replace(/^已有｜/,'')));const card=el('article',undefined,'focus-card');if(row.members.length>1)card.append(el('p',`${state.item+1} / ${row.members.length}`,'eyebrow'));if(m.review!=='accepted-outline')card.append(el('span',m.review==='missing-reference'?'內容準備中':'內容待核對','badge'));card.append(el('h2',m.title));if(m.detail.sense){card.append(el('p',m.detail.sense.definition,'meaning'));for(const [key,label] of [['conditions','使用時注意'],['exclusions','不要混淆']]){const text=clean(m.detail.sense[key]||'');if(text){const d=el('details');d.append(el('summary',label),el('p',text));card.append(d);}}const forms=el('details');forms.append(el('summary','其他形式與用法'));for(const f of m.detail.forms||[]){forms.append(el('p',f.text));const t=clean(f.conditions||'');if(t)forms.append(el('p',t));}card.append(forms);}else{const d=el('details');d.append(el('summary','看看學習重點'));for(const x of m.detail.inLessonSupport||[]){const t=clean(x);if(t)d.append(el('p',t));}card.append(d);const pre=el('details');pre.append(el('summary','開始前，需要會什麼？'));for(const x of m.detail.prerequisites||[]){const t=clean(typeof x==='string'?x:x.description||'');if(t)pre.append(el('p',t));}if(!m.detail.prerequisites?.length)pre.append(el('p','可以從這裡開始。'));card.append(pre);if(m.id==='outline:c:theme01:02:ja'){const link=el('a','開始這堂課 →','primary');link.href='/lingourmet-study/learning-map/lesson/index.html';card.append(link);}else card.append(el('p','這堂課正在準備中','muted'));}root.append(card);if(row.members.length>1)root.append(pager(state.item,row.members.length,item=>move({item})));return;}
 root.append(el('h1','一步一步，學會表達。'));const tabs=el('nav',undefined,'tabs');for(const [kind,name]of Object.entries(names)){const b=button(name,()=>move({kind,page:0,row:null}));b.setAttribute('aria-pressed',String(kind===state.kind));tabs.append(b);}root.append(tabs);
 const filters=el('div',undefined,'compact-filters');const label=el('label','程度');const level=el('select');level.setAttribute('aria-label','程度');for(const band of ['A1','A2','B1','B2']){const o=el('option',band);o.value=band;o.selected=state.band===band;level.append(o);}level.onchange=()=>move({band:level.value,page:0});label.append(level);const search=el('input');search.type='search';search.placeholder='搜尋主題';search.setAttribute('aria-label','搜尋主題');search.value=state.search;search.onchange=()=>move({search:search.value,page:0});filters.append(label,search);root.append(filters);
 const list=rows();root.append(el('p',`${list.length} 個主題`,'muted'));const cards=el('div',undefined,'topic-list');for(const row of list.slice(state.page*pageSize,(state.page+1)*pageSize)){const b=button('',()=>move({row:row.id,item:0}),'topic');b.append(el('strong',row.title.replace(/^已有｜/,'')),el('span',state.kind==='vocabulary'?`${row.members.length} 個詞義 · 點開學習`:'查看內容 →'));cards.append(b);}if(!list.length)cards.append(el('p','這個程度的內容還在準備中。可以選擇其他程度，或換個關鍵字。','empty'));root.append(cards);if(list.length>pageSize)root.append(pager(state.page,Math.ceil(list.length/pageSize),page=>move({page})));
 }
 history.replaceState(state,'');render();return {getState:()=>({...state})};
}
if(typeof document!=='undefined'&&document.querySelector('#app'))loadMatrices().then(data=>mount(data)).catch(e=>{document.querySelector('#app').replaceChildren(el('p',e.message,'empty'));});
