import {h,t,localize,UI,LOCALES} from './i18n.mjs';
import {unitText,sourceGroups,tokensForRange,withCatalog,validateLesson,resolveMeaning} from './model.mjs';
const list=(values,locale,cls='')=>values?.length?`<ul class="${cls}">${values.map(v=>`<li>${t(v,locale)}</li>`).join('')}</ul>`:'';
const entryURL=(id,locale,uiLocale)=>`./knowledge.html?entry=${encodeURIComponent(id)}&lang=${encodeURIComponent(locale)}&ui=${encodeURIComponent(uiLocale)}`;
function tokenText(token){
 if(token.ruby?.length)return token.ruby.map(r=>r.reading?`<ruby>${h(r.text)}<rp>（</rp><rt>${h(r.reading)}</rt><rp>）</rp></ruby>`:h(r.text)).join('');
 if(token.reading&&/[一-龯]/u.test(token.text))return `<ruby>${h(token.text)}<rp>（</rp><rt>${h(token.reading)}</rt><rp>）</rp></ruby>`;
 return h(token.text);
}
export function unitHTML(id,data,{interactive=true}={}){
 const unit=data.units[id];
 return `<span class="unit" ${interactive?`id="unit-${h(id)}" data-unit="${h(id)}"`:""} lang="ja">${unit.tokens.map(tok=>interactive?`<button class="token" type="button" data-select-kind="token" data-select-unit="${h(id)}" data-select-id="${h(tok.id)}">${tokenText(tok)}</button>`:`<span>${tokenText(tok)}</span>`).join('')}</span>`;
}
function rangeButtons(uid,data,locale,kind){const unit=data.units[uid];return(unit[kind==='chunk'?'chunks':'spans']??[]).map(range=>`<button class="range-choice" type="button" data-select-kind="${kind}" data-select-unit="${h(uid)}" data-select-id="${h(range.id)}"><span lang="ja">${h(tokensForRange(unit,range.from,range.to).map(t=>t.text).join(''))}</span></button>`).join('');}
function unitSupport(uid,data,locale,uiLocale){const u=UI[uiLocale],loc=data.localizations[locale]?.units?.[uid];const chunk=rangeButtons(uid,data,locale,'chunk'),span=rangeButtons(uid,data,locale,'span');return `<div class="unit-support"><p class="support-source"><span lang="ja">${h(unitText(data.units[uid]))}</span></p><p>${h(loc?.meaning??loc?.translation??u.missing)}</p>${chunk?`<p class="support-label">${h(u.chunk)}</p><div class="range-row">${chunk}</div>`:''}${span?`<p class="support-label">${h(u.span)}</p><div class="range-row">${span}</div>`:''}</div>`;}
function speakerName(speakerId,data){const speaker=data.speakers?.[speakerId];if(speaker?.nameRef){const ref=speaker.nameRef;return tokensForRange(data.units[ref.unit],ref.from,ref.to).map(t=>t.text).join('');}return speaker?.name??speaker??speakerId;}
function renderSource(id,data,locale,uiLocale){
 const source=data.sources[id],loc=data.localizations[locale]?.sources?.[id],groups=sourceGroups(source),u=UI[uiLocale];
 return `<article class="material" id="source-${h(id)}" data-source-type="${h(source.type)}"><h3>${h(loc?.title??u.missing)}</h3>${loc?.summary?`<p class="context">${h(loc.summary)}</p>`:''}<div class="dialogue ${source.type==='dialogue'?'':'prose'}">${groups.map(group=>`<div class="line" id="group-${h(group.id)}">${group.speakerId?`<p class="speaker">${h(speakerName(group.speakerId,data))}</p>`:''}<div class="source passage">${group.unitRefs.map(uid=>unitHTML(uid,data)).join('')}</div></div>`).join('')}</div><details class="material-meanings"><summary>${h(u.meaning)}</summary>${groups.flatMap(g=>g.unitRefs).map(uid=>unitSupport(uid,data,locale,uiLocale)).join('')}</details></article>`;
}
function sourceRefs(refs,data,locale,uiLocale){return (refs??[]).map(ref=>{const text=tokensForRange(data.units[ref.unit],ref.from,ref.to).map(t=>t.text).join('');return `<a class="source-link" href="#unit-${h(ref.unit)}" data-source-unit="${h(ref.unit)}"${ref.from!==undefined?` data-source-from="${h(ref.from)}" data-source-to="${h(ref.to)}"`:''}>${h(UI[uiLocale].source)} · <span lang="ja">${h(text)}</span></a>`;}).join('');}
function renderExamples(refs,data,locale,uiLocale){return (refs??[]).map((id,index)=>{const example=data.examples?.[id];if(!example)return '';const loc=data.localizations[locale]?.examples?.[id];const groups=example.turns??[{unitRefs:example.unitRefs}];return `<div class="entry-example"><p class="example-label">${h(UI[uiLocale].examples)} ${index+1}</p>${groups.map(group=>`<div class="example-turn">${group.speakerId?`<p class="speaker">${t(example.roleLabels?.[group.speakerId]??group.speakerId,locale)}</p>`:''}<div class="source" lang="ja">${group.unitRefs.map(uid=>unitHTML(uid,data,{interactive:false})).join('')}</div>${group.unitRefs.map(uid=>`<p class="translation">${h(data.localizations[locale]?.units?.[uid]?.meaning??UI[uiLocale].missing)}</p>`).join('')}</div>`).join('')}</div>`;}).join('');}

function entryBody(entry,data,locale,uiLocale){const loc=entry.localizations?.[locale],u=UI[uiLocale];return `${loc?.explanation?`<p class="entry-explanation">${h(loc.explanation).replace(/\n/g,'<br>')}</p>`:`<p class="missing">${h(u.missing)}</p>`}${loc?.usage?`<p>${h(loc.usage)}</p>`:''}${loc?.limits?`<p>${h(loc.limits)}</p>`:''}${renderExamples(entry.exampleRefs,data,locale,uiLocale)}`;}
function renderTeaching(data,catalog,locale,uiLocale){const u=UI[uiLocale];return(data.teachingRefs??[]).map((item,index)=>{const entry=catalog.entries[item.entryId];const loc=entry.localizations?.[locale];return `<article class="card teaching-entry" id="teaching-${h(item.id??index)}"><h3><a href="${entryURL(item.entryId,locale,uiLocale)}">${h(loc?.title??u.missing)}</a></h3>${sourceRefs(item.sourceRefs,data,locale,uiLocale)}${item.context?`<p class="lesson-context"><strong>${h(u.context)}</strong> · ${t(item.context,locale)}</p>`:''}${entryBody(entry,data,locale,uiLocale)}<a class="entry-link" href="${entryURL(item.entryId,locale,uiLocale)}">${h(u.openEntry)} →</a></article>`;}).join('');}
function renderPractice(data,locale,uiLocale){const u=UI[uiLocale];return(data.practice?.items??[]).map((item,index)=>{const self=item.stage==='self-expression';return `<article class="card" id="practice-${h(item.id)}"><h3>${index+1}. ${t(item.title??item.stage,locale)}</h3><p>${t(item.prompt,locale)}</p>${item.material?`<p class="source" lang="ja">${h(item.material)}</p>`:''}${item.options?.length?`<ol class="options">${item.options.map(option=>`<li>${t(option.text??option,locale)}</li>`).join('')}</ol>`:''}<label class="draft-label" for="draft-${h(item.id)}">${h(u.write)}</label><textarea class="practice-draft" id="draft-${h(item.id)}" data-draft-id="${h(item.id)}" autocomplete="off" spellcheck="false"></textarea><details class="${self?'sample':'solution'}"><summary>${h(self?u.sample:u.reveal)}</summary><div class="answer"><p>${t(item.answer,locale)}</p>${item.explanation?`<p>${t(item.explanation,locale)}</p>`:''}${item.alternatives?.length?`<strong>${h(u.alternatives)}</strong>${list(item.alternatives,locale)}`:''}${self?`<h4>${h(u.selfCheck)}</h4>${list(item.checklist,locale,'checklist')}`:''}${sourceRefs(item.sourceRefs,data,locale,uiLocale)}</div></details></article>`;}).join('');}
export function selectionHTML(data,locale,selection,uiLocale=locale){const result=resolveMeaning(data,locale,selection),u=UI[uiLocale];return `<button class="selection-close" type="button" data-close-selection aria-label="${h(u.close)}">×</button><p class="eyebrow">${h(u[selection.kind]??u.selection)}</p><p class="source" lang="ja">${h(result.text)}</p>${result.reading?`<p lang="ja">${h(result.reading)}</p>`:''}<p>${h(result.meaning??u.missing)}</p>`;}
export function renderLesson(raw,catalog,locale='zh-Hant',uiLocale=locale){
 if(!LOCALES.includes(uiLocale))uiLocale='zh-Hant';const data=withCatalog(raw,catalog),errors=validateLesson(data,catalog);if(errors.length)throw new Error(errors.join('\n'));
 const u=UI[uiLocale];if(!raw.localizations?.[locale])return `<section class="missing-language" role="status"><h1>${h(u.missing)}</h1></section>`;const loc=data.localizations[locale];
 return `<div class="eyebrow">${h(u.draft)}</div><h1 lang="${h(locale)}">${h(loc.title??u.missing)}</h1><p class="context">${h(loc.intro??'')}</p>${loc.goals?.length?`<h2>${h(u.goals)}</h2>${list(loc.goals,locale)}`:''}<nav class="stage-nav" aria-label="${h(u.draft)}"><a href="#content">1 ${h(u.content)}</a><a href="#teaching">2 ${h(u.teaching)}</a><a href="#practice">3 ${h(u.practice)}</a></nav><section class="stage" id="content"><h2>1 · ${h(u.content)}</h2>${data.sourceOrder.map(id=>renderSource(id,data,locale,uiLocale)).join('')}${loc.readingNotes?`<details class="reading-notes"><summary>${h(u.readingNotes)}</summary><p>${h(loc.readingNotes)}</p></details>`:''}<a class="go-next" href="#teaching">${h(u.nextTeaching)}</a></section><section class="stage" id="teaching"><h2>2 · ${h(u.teaching)}</h2>${renderTeaching(data,catalog,locale,uiLocale)}<a class="go-next" href="#practice">${h(u.nextPractice)}</a></section><section class="stage" id="practice"><h2>3 · ${h(u.practice)}</h2>${renderPractice(data,locale,uiLocale)}<a class="go-next" href="#content">${h(u.top)}</a></section><aside id="selection-panel" class="selection-panel" role="region" aria-label="${h(u.selection)}" aria-live="polite" hidden></aside><footer>${h(u.footer)}</footer>`;
}
export function renderEntry(catalog,id,locale='zh-Hant',uiLocale=locale){
 const u=UI[uiLocale],entry=catalog.entries?.[id];if(!entry)return `<h1>${h(u.entryMissing)}</h1><a href="./?lang=${encodeURIComponent(locale)}&ui=${encodeURIComponent(uiLocale)}">${h(u.back)}</a>`;
 if(!catalog.localizations?.[locale]||!entry.localizations?.[locale])return `<section class="missing-language" role="status"><h1>${h(u.missing)}</h1></section>`;
 const loc=entry.localizations[locale],data={...catalog};
 return `<a href="./?lang=${encodeURIComponent(locale)}&ui=${encodeURIComponent(uiLocale)}">${h(u.back)}</a><p class="eyebrow">${h(u.entryDraft)}</p><h1 lang="${h(locale)}">${h(loc?.title??u.missing)}</h1>${entryBody(entry,data,locale,uiLocale)}${entry.relatedRefs?.length?`<h2>${h(u.related)}</h2><ul>${entry.relatedRefs.map(ref=>`<li><a href="${entryURL(ref,locale,uiLocale)}">${h(catalog.entries[ref]?.localizations?.[locale]?.title??u.missing)}</a></li>`).join('')}</ul>`:''}`;
}
