import {h,UI,LOCALES} from './i18n.mjs';
import {resolveSelectedRef} from './selected-practice.mjs';
import {tokenText,studyNavigation} from './renderer.mjs';
export function selectedStoreNotice(store,uiLocale){const u=UI[uiLocale],state=store.state;if(!state.error)return '';return `<p role="alert">${h(state.error==='read'?u.selectedReadError:u.selectedSaveError)}</p><button type="button" data-selected-retry>${h(u.selectedRetry)}</button>`;}
export function selectedToggleHTML(store,ref,uiLocale){if(!ref)return '';const u=UI[uiLocale],saved=store.has(ref),disabled=!!store.state.error||!!store.state.pending;return `<button type="button" class="selected-toggle" data-toggle-selected aria-pressed="${saved}"${disabled?' disabled':''}>${h(saved?u.removeSelected:u.addSelected)}</button>${selectedStoreNotice(store,uiLocale)}`;}
export function selectedOverviewHTML(data,analysis,store,projection,locale,uiLocale,ctx={}){
 const u=UI[uiLocale];if(!LOCALES.includes(locale))return `<section class="missing-language" role="status"><h1>${h(u.missing)}</h1></section>`;
 const state=store.state,items=store.list(),disabled=!!state.error||!!state.pending;
 const rows=items.map(item=>{const resolved=resolveSelectedRef(data,item.ref,{lessonId:state.lessonId,analysis}),ready=resolved.status==='available';const meaning=ready&&Object.hasOwn(resolved.meanings,locale)?resolved.meanings[locale]:null;const issue=projection.unavailable.find(x=>x.ref&&JSON.stringify(x.ref)===JSON.stringify(item.ref));return `<li class="selected-item"><div>${ready?`<button type="button" class="selected-source" data-selected-open="${h(item.id)}" lang="ja">${resolved.tokens.map(tokenText).join('')}</button>${ctx.audio?.(data,resolved.sourceRef)??''}<p lang="${h(locale)}">${h(meaning??u.missing)}</p>`:`<p>${h(resolved.code==='stale_source_revision'?u.selectedStale:u.selectedUnavailable)}</p>`}${ready&&issue&&meaning?`<p class="muted">${h(issue.code==='assembly_unavailable'?u.selectedAssemblyUnavailable:u.selectedUnavailable)}</p>`:''}</div><button type="button" data-selected-remove="${h(item.id)}"${disabled?' disabled':''} aria-label="${h(u.removeSelected)}">${h(u.removeSelected)}</button></li>`;}).join('');
 return `${studyNavigation(uiLocale)}<section id="selected-list" class="stage"><h1 tabindex="-1" data-selected-focus>${h(u.selectedTitle)}</h1>${selectedStoreNotice(store,uiLocale)}${items.length?`<ul class="selected-items">${rows}</ul>`:state.error?'':`<p>${h(u.selectedEmpty)}</p>`}<div class="selected-practice-actions"><button type="button" data-selected-start="cards"${disabled||!projection.cards.length?' disabled':''}>${h(u.practiceSelectedCards)}</button><button type="button" data-selected-start="questions"${disabled||!projection.wordBank.length?' disabled':''}>${h(u.practiceSelectedSentences)}</button></div></section><p id="audio-status" role="status"></p>`;
}
